package protocol

type Type string

const (
	Login            Type = "login"
	LoginOK          Type = "login_ok"
	Ping             Type = "ping"
	Pong             Type = "pong"
	EnterGroup       Type = "enter_group"
	EnterGroupOk     Type = "enter_group_ok"
	LeaveGroup       Type = "leave_group"
	LeaveGroupOk     Type = "leave_group_ok"
	SendChat         Type = "send_chat"
	SendChatOk       Type = "send_chat_ok"
	CastChat         Type = "cast_chat"
	Error            Type = "error"
	PinChat          Type = "pin_chat"
	PinChatOk        Type = "pin_chat_ok"
	UnpinChat        Type = "unpin_chat"
	UnpinChatOk      Type = "unpin_chat_ok"
	PinChatCast      Type = "pin_chat_cast"
	UnpinChatCast    Type = "unpin_chat_cast"
	DelChat          Type = "del_chat"
	DelChatOk        Type = "del_chat_ok"
	DelChatCast      Type = "del_chat_cast"
	BanUser          Type = "ban_user"
	BanUserOk        Type = "ban_user_ok"
	BanUserAck       Type = "ban_user_ack"
	UnbanUser        Type = "unban_user"
	UnbanUserOk      Type = "unban_user_ok"
	UnbanUserAck     Type = "unban_user_ack"
	KickUser         Type = "kick_user"
	KickUserOk       Type = "kick_user_ok"
	KickUserAck      Type = "kick_user_ack"
	KickUserCast     Type = "kick_user_cast"
	EnterLobby       Type = "enter_lobby"
	EnterLobbyOk     Type = "enter_lobby_ok"
	EnterMyGroup     Type = "enter_my_group"
	EnterMyGroupOk   Type = "enter_my_group_ok"
	EnterSysGroup    Type = "enter_sys_group"
	EnterSysGroupOk  Type = "enter_sys_group_ok"
	EnterSelf        Type = "enter_self"
	EnterSelfOk      Type = "enter_self_ok"
	UpdateLastRead   Type = "update_last_read"
	UpdateLastReadOk Type = "update_last_read_ok"
	GetChatHistory   Type = "get_chat_history"
	GetChatHistoryOk Type = "get_chat_history_ok"
	UserQuitCast     Type = "user_quit_cast"
	Resume           Type = "resume"
)
