package protocol

type MsgType string

const (
	Login            MsgType = "login"
	LoginOK          MsgType = "login_ok"
	EnterGroup       MsgType = "enter_group"
	EnterGroupOk     MsgType = "enter_group_ok"
	LeaveGroup       MsgType = "leave_group"
	LeaveGroupOk     MsgType = "leave_group_ok"
	SendChat         MsgType = "send_chat"
	SendChatOk       MsgType = "send_chat_ok"
	CastChat         MsgType = "cast_chat"
	Error            MsgType = "error"
	PinChat          MsgType = "pin_chat"
	PinChatOk        MsgType = "pin_chat_ok"
	UnpinChat        MsgType = "unpin_chat"
	UnpinChatOk      MsgType = "unpin_chat_ok"
	PinChatCast      MsgType = "pin_chat_cast"
	UnpinChatCast    MsgType = "unpin_chat_cast"
	DelChat          MsgType = "del_chat"
	DelChatOk        MsgType = "del_chat_ok"
	DelChatCast      MsgType = "del_chat_cast"
	BanUser          MsgType = "ban_user"
	BanUserOk        MsgType = "ban_user_ok"
	BanUserAck       MsgType = "ban_user_ack"
	UnbanUser        MsgType = "unban_user"
	UnbanUserOk      MsgType = "unban_user_ok"
	UnbanUserAck     MsgType = "unban_user_ack"
	KickUser         MsgType = "kick_user"
	KickUserOk       MsgType = "kick_user_ok"
	KickUserAck      MsgType = "kick_user_ack"
	KickUserCast     MsgType = "kick_user_cast"
	EnterLobby       MsgType = "enter_lobby"
	EnterLobbyOk     MsgType = "enter_lobby_ok"
	EnterMyGroup     MsgType = "enter_my_group"
	EnterMyGroupOk   MsgType = "enter_my_group_ok"
	EnterSelf        MsgType = "enter_self"
	EnterSelfOk      MsgType = "enter_self_ok"
	UpdateLastRead   MsgType = "update_last_read"
	UpdateLastReadOk MsgType = "update_last_read_ok"
	UserQuitCast     MsgType = "user_quit_cast"
	Resume           MsgType = "resume"
	ResumeOK         MsgType = "resume_ok"
	JoinGroup        MsgType = "join_group"
	JoinGroupOK      MsgType = "join_group_ok"
	Logout           MsgType = "logout"
	LogoutOK         MsgType = "logout_ok"
	UpdateGroup      MsgType = "update_group"
	UpdateGroupOk    MsgType = "update_group_ok"
	UpdateGroupCast  MsgType = "update_group_cast"
)
